# Teller configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in

debug = true
profile = false
enabled = true
# logfile = "./teller.log"  # logfile can be an absolute path or relative to the working directory
dbfile = "teller.db"  # dbfile is saved inside ~/.teller-mdl, do not include a path
btc_addresses = "example_btc_addresses.json" # REQUIRED: path to btc addresses file
eth_addresses = "test_eth.json" # REQUIRED: path to eth addresses file
sky_addresses = "example_sky_addresses.json"
waves_addresses = "example_waves_addresses.json"
waves_mdl_addresses = "example_waves_mdl_addresses.json"

[teller]
max_bound_addrs = 2 # 0 means unlimited
bind_enabled = true # Disable this to prevent binding of new addresses

[mdl_rpc]
address = "127.0.0.1:8330"

[btc_rpc]
enabled = false
server = "127.0.0.1:8334"
user = "1" # REQUIRED
pass = "1" # REQUIRED
cert = "rpc.cert" # REQUIRED
key = "rpc.key" # REQUIRED

[eth_rpc]
enabled = false
server = "127.0.0.1" # REQUIRED
port = "8545" # REQUIRED

[sky_rpc]
enabled = true
server = "127.0.0.1" # REQUIRED
port = "6430" # REQUIRED

[waves_rpc]
enabled = false # not yet implemented
server = "127.0.0.1" # REQUIRED
port = "8081" # REQUIRED

[waves_mdl_rpc]
enabled = false # not yet implemented
server = "127.0.0.1" # REQUIRED
port = "8081" # REQUIRED

[btc_scanner]
scan_period = "20s"
initial_scan_height = 492478
confirmations_required = 1

[eth_scanner]
scan_period = "5s"
initial_scan_height=4654259
confirmations_required = 1

[sky_scanner]
scan_period = "5s"
initial_scan_height=18224
confirmations_required = 1

[waves_scanner]
scan_period = "5s"
initial_scan_height=4654259
confirmations_required = 1

[waves_mdl_scanner]
scan_period = "5s"
initial_scan_height=4654259
confirmations_required = 1

[mdl_exchanger]
mdl_btc_exchange_rate = "454545.454" # REQUIRED: MDL/BTC exchange rate as a string, can be an int, float or a rational fraction
mdl_btc_exchange_rate_usd = "" # TODO:
mdl_btc_exchange_label = "Bitcoin (Under Maintenance)"
mdl_btc_exchange_enabled = true

mdl_eth_exchange_rate = "10000" # REQUIRED: MDL/ETH exchange rate as a string, can be an int, float or a rational fraction
mdl_eth_exchange_rate_usd = ""  # TODO:
mdl_eth_exchange_label = "Ethereum (Syncing)"
mdl_eth_exchange_enabled = false

mdl_sky_exchange_rate = "100" # REQUIRED: MDL/SKY exchange rate as a string, can be an int, float or a rational fraction
mdl_sky_exchange_rate_usd = ""  # TODO:
mdl_sky_exchange_label = "Skycoin (Experimental)"
mdl_sky_exchange_enabled = false

mdl_waves_exchange_rate = "100" # REQUIRED: MDL/WAVES exchange rate as a string, can be an int, float or a rational fraction
mdl_waves_exchange_rate_usd = ""  # TODO:
mdl_waves_exchange_label = "Waves (Temporary Disabled)"
mdl_waves_exchange_enabled = false

mdl_waves_mdl_exchange_rate = "100" # REQUIRED: MDL/WAVES MDL exchange rate as a string, can be an int, float or a rational fraction
mdl_waves_mdl_exchange_rate_usd = "" # TODO:
mdl_waves_mdl_exchange_label = "MDL.life - pre-MDL token on Waves (Temporary Disabled, but coming soon)"
mdl_waves_mdl_exchange_enabled = false

wallet = "mdl-example.wlt" # REQUIRED: path to local hot wallet file
# max_decimals = 3  # Number of decimal places to truncate MDL to
# tx_confirmation_check_wait = "5s"
send_enabled = true # Disable this to disable sending of coins (all other processing functions normally)
# buy_method = "direct" # Options are "direct" or "passthrough"

[web]
# behind_proxy = false  # This must be set to true when behind a proxy for ratelimiting to work
http_addr = ":1550"
# static_dir = "./web/build"
# throttle_max = 60
# throttle_duration = "60s"
https_addr = "" # OPTIONAL: Serve on HTTPS
auto_tls_host = "" # OPTIONAL: Hostname to use for automatic TLS certs. Used when tls_cert, tls_key unset
tls_cert = ""
tls_key = ""

[admin_panel]
host = "127.0.0.1:7711"


[dummy]
# fake sender and scanner with admin interface adding fake deposits,
# and viewing and confirmed mdl transactions
sender = false
scanner = false
#http_addr = "127.0.0.1:4121"
