
# gopkg.toml example
#
# refer to https://github.com/golang/dep/blob/master/docs/gopkg.toml.md
# for detailed gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgx", "bitbucket.org/user/project/pkga/pkgy"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  branch = "master"
  name = "github.com/nytimes/gziphandler"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  revision = "c7588cbf7690cd9f047a28efa2dcd8f2435a4e5e"
  name = "github.com/btcsuite/btcd"

[[override]]
  revision = "5ffa719c3882fd2ec1e8b9f4978066701c31a343"
  name = "github.com/btcsuite/btcutil"

[[constraint]]
  name = "github.com/google/gops"
  version = "0.3.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/gz-c/logrus-prefixed-formatter"
  version = "v0.7.1"

[[constraint]]
  name = "github.com/gz-c/tollbooth"
  version = "v2.3.0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.7.3"

[[constraint]]
  branch = "master"
  name = "github.com/modeneis/waves-go-client"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
